# Generated by Django 5.1.4 on 2024-12-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_posts_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="banner",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
